apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "alibi_explain"
spec:          
  explainer:
    minReplicas: 1
    alibi:
      type: AnchorTabular
      storageUri: "gs://kfserving-examples/models/sklearn/1.3/income/explainer"
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 2
          memory: 2Gi
